#!/usr/bin/env python3
"""
createGitIgnore.py — write a .gitignore tailored to PyTorchUI.

Creates or overwrites .gitignore with rules for:

  * Python bytecode, caches, build artifacts
  * virtualenvs
  * IDE / editor scratch files
  * OS cruft
  * project-specific generated files:
      main.py             (built by create.py from installed libraries)
      generated.py        (emitted by the editor on Ctrl+G)
      autosave.json       (Settings -> Auto Save buffer)
      settings.json       (local override; canonical copy lives in
                           ~/.pytorchui/settings.json)
      *.bak_*             (backups written by the patch scripts)

By default existing files are left alone.  Pass --force to overwrite,
or --dry-run to preview without writing.

Usage:
    python3 createGitIgnore.py
    python3 createGitIgnore.py --force
    python3 createGitIgnore.py --dry-run
    python3 createGitIgnore.py --dir /path/to/project
"""

import argparse
import os
import sys


# --------------------------------------------------------------------------- #
#  Content                                                                    #
# --------------------------------------------------------------------------- #

GITIGNORE = '''\
# ============================================================== #
#  PyTorchUI — .gitignore                                        #
#                                                                #
#  Generated by createGitIgnore.py.  Edit with care; re-running  #
#  the script with --force will overwrite this file.             #
# ============================================================== #


# ---------------------------------------------------------------- #
#  Python                                                           #
# ---------------------------------------------------------------- #

__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
pip-log.txt
pip-delete-this-directory.txt


# ---------------------------------------------------------------- #
#  Virtual environments                                             #
# ---------------------------------------------------------------- #

.venv/
venv/
ENV/
env/
.python-version


# ---------------------------------------------------------------- #
#  Testing / coverage                                               #
# ---------------------------------------------------------------- #

.pytest_cache/
.coverage
.coverage.*
htmlcov/
.tox/
.nox/
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/


# ---------------------------------------------------------------- #
#  PyQt / Qt                                                        #
# ---------------------------------------------------------------- #

*.qm
*.qmlc
*.jsc
moc_*.py
qrc_*.py
ui_*.py
*.ui.pyc


# ---------------------------------------------------------------- #
#  Jupyter (in case you sketch ideas in a notebook)                 #
# ---------------------------------------------------------------- #

.ipynb_checkpoints/
*.ipynb.bak


# ---------------------------------------------------------------- #
#  IDE / editors                                                    #
# ---------------------------------------------------------------- #

.vscode/
.idea/
*.iml
*.swp
*.swo
*~
*.orig
*.rej
.tags
.tags.lock


# ---------------------------------------------------------------- #
#  Operating system cruft                                           #
# ---------------------------------------------------------------- #

.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/


# ---------------------------------------------------------------- #
#  Project-specific                                                 #
# ---------------------------------------------------------------- #

# main.py is regenerated by `python create.py` from whatever
# libraries are installed.  Committing it produces a 40,000-line
# diff every time torch updates, so we ignore it here.
#
# If you would rather run the editor out of the box without
# invoking create.py first, delete the next line and commit a
# pinned main.py.
/main.py

# Emitted by the editor's Ctrl+G.  Regenerate from the graph
# itself; never merge conflicts worth keeping.
/generated.py

# Auto Save buffer written by Settings -> Auto Save when no
# document is currently open.
/autosave.json

# Local override of the persistent settings.  The canonical file
# lives at ~/.pytorchui/settings.json and is not part of the
# repository.
/settings.json
/.pytorchui/

# Backups written by the various patch scripts (edit.py,
# fix_*.py, ...).  They exist to be deleted once a patch is
# verified.
*.bak_*
*.bak

# Local PyTorch / HF caches if you experiment with models inside
# the project directory.  Normally these live under
# ~/.cache/ or ~/.pytorchui/.
/.cache/
/.torch/
/.huggingface/
'''


# --------------------------------------------------------------------------- #
#  Main                                                                       #
# --------------------------------------------------------------------------- #

def main():
    parser = argparse.ArgumentParser(
        prog="createGitIgnore.py",
        description="Write a .gitignore tailored to PyTorchUI.",
    )
    parser.add_argument(
        "-d", "--dir", dest="target_dir", default=".",
        help="directory to write into (default: current directory)",
    )
    parser.add_argument(
        "-f", "--force", action="store_true",
        help="overwrite an existing .gitignore",
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="show what would happen without writing anything",
    )
    args = parser.parse_args()

    target = os.path.abspath(args.target_dir)
    if not os.path.isdir(target):
        print("! target directory does not exist: %s" % target)
        sys.exit(1)

    full = os.path.join(target, ".gitignore")
    exists = os.path.isfile(full)

    print("Target: %s" % target)
    print()

    if exists and not args.force:
        print("  --  .gitignore exists, skipped")
        print()
        print("Existing .gitignore was preserved.  Pass --force to")
        print("overwrite it.")
        return

    if args.dry_run:
        verb = "would overwrite" if exists else "would create"
        print("  ok  .gitignore  %s (%d bytes)"
              % (verb, len(GITIGNORE)))
        print()
        print("Dry run: nothing written.")
        return

    with open(full, "w", encoding="utf-8") as f:
        f.write(GITIGNORE)

    verb = "overwrote" if exists else "created"
    print("  [+] .gitignore  %s (%d bytes)" % (verb, len(GITIGNORE)))
    print()

    # Helpful follow-ups if the user is inside a fresh git repo.
    git_dir = os.path.join(target, ".git")
    if os.path.isdir(git_dir):
        print("Next steps inside the repository:")
        print("    git status")
        print("    git add .gitignore")
        print("    git rm -r --cached . >/dev/null   # if files are already tracked")
        print("    git commit -m 'Add .gitignore'")
    else:
        print("Note: this directory is not a git repository yet.")
        print("Run `git init` first if you plan to publish the project.")


if __name__ == "__main__":
    main()