#!/usr/bin/env python3
"""
cleanup_root.py — tidy up the PyTorchUI project root.

By default this is a dry run.  Pass --apply to make the changes.

What it does:

  1.  Moves the banner into docs/banner.png
  2.  Moves main.db into data/main.db (and updates create.py's
      default DB_FILE and main.py's loader path).
  3.  Deletes *.bak_* files that were generated by patch scripts.
  4.  Deletes __pycache__/ and *.pyc.
  5.  Updates .gitignore to ignore data/, *.bak_*, autosave.json,
      generated.py, and the root-level db/loader leftovers.

Usage:
    python3 cleanup_root.py
    python3 cleanup_root.py --apply
"""

import argparse
import os
import re
import shutil
import subprocess
import sys


BANNER_SRC = "pytorchui_banner_1920x1080.png"
BANNER_DST = "docs/banner.png"

DB_SRC = "main.db"
DB_DST = "data/main.db"

DELETE_GLOBS = (
    ".bak_strdefaults", ".bak_fts5", ".bak_keygrab",
    ".bak_keygrab2", ".bak_kgsys", ".bak_winmod", ".bak_rawkbd",
    ".bak_rawkbd2", ".bak_kbd3", ".bak_evdev", ".bak_speed",
    ".bak_multi", ".bak_multi4", ".bak_multi5", ".bak_ask",
    ".bak_pvsh", ".bak_pvsh_final", ".bak_overlayprint",
    ".bak_grab", ".bak_capture2",
)

DELETE_EXACT = (
    "graph.json.autosave",
    "graph.json.bak_strdefaults",
)


def find_baks():
    out = []
    for name in sorted(os.listdir(".")):
        if not os.path.isfile(name):
            continue
        if name in DELETE_EXACT:
            out.append(name); continue
        for suffix in DELETE_GLOBS:
            if name.endswith(suffix):
                out.append(name); break
    return out


def find_pycache():
    out = []
    for root, dirs, files in os.walk("."):
        if ".git" in root.split(os.sep):
            continue
        if os.path.basename(root) == "__pycache__":
            out.append(root)
        for f in files:
            if f.endswith(".pyc"):
                out.append(os.path.join(root, f))
    return out


def move(src, dst, apply):
    if not os.path.isfile(src):
        return False
    print("  %-40s -> %s" % (src, dst))
    if apply:
        os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
        shutil.move(src, dst)
    return True


def remove(path, apply):
    if not os.path.exists(path):
        return False
    print("  remove %s" % path)
    if apply:
        if os.path.isdir(path):
            shutil.rmtree(path)
        else:
            os.remove(path)
    return True


def patch_file(path, subs, apply):
    if not os.path.isfile(path):
        return 0
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    orig = src
    for old, new in subs:
        if old in src and new not in src:
            src = src.replace(old, new, 1)
    if src == orig:
        return 0
    print("  patch %s (%d change%s)"
          % (path, 1, "" if src == orig else "s"))
    if apply:
        shutil.copy(path, path + ".bak_cleanup")
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)
    return 1


def gitignore_append(apply):
    path = ".gitignore"
    block = (
        "\n# ---------------------------------------------------------------- #\n"
        "#  Cleanup rules                                                    #\n"
        "# ---------------------------------------------------------------- #\n"
        "\n"
        "data/\n"
        "docs/banner.png\n"
        ".pytorchui/\n"
        "autosave.json\n"
        "generated.py\n"
        "*.bak_*\n"
        "**/__pycache__/\n"
        "*.pyc\n"
    )
    if not os.path.isfile(path):
        print("  ! .gitignore not present")
        return 0
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    if "/data/" in src or "docs/banner.png" in src:
        return 0
    print("  append .gitignore rules")
    if apply:
        with open(path, "a", encoding="utf-8") as f:
            f.write(block)
    return 1


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--apply", action="store_true",
                   help="actually make the changes")
    args = p.parse_args()

    print("mode:", "APPLY" if args.apply else "dry run")
    print()

    print("Moves:")
    move(BANNER_SRC, BANNER_DST, args.apply)
    move(DB_SRC, DB_DST, args.apply)
    print()

    print("Delete backups:")
    for name in find_baks():
        remove(name, args.apply)
    print()

    print("Delete __pycache__:")
    for name in find_pycache():
        remove(name, args.apply)
    print()

    print("Patch paths to data/main.db:")
    patch_file("create.py", [
        ('DB_FILE      = "main.db"', 'DB_FILE      = "data/main.db"'),
        ("DB_FILE      = 'main.db'", "DB_FILE      = 'data/main.db'"),
    ], args.apply)
    patch_file("main.py", [
        ("_load_specs('main.json', 'main.db')",
         "_load_specs('data/main.json', 'data/main.db')"),
        ('_load_specs("main.json", "main.db")',
         '_load_specs("data/main.json", "data/main.db")'),
    ], args.apply)
    print()

    print(".gitignore:")
    gitignore_append(args.apply)
    print()

    if args.apply:
        print("Done.  Review with:  git status")
    else:
        print("Dry run.  Re-run with --apply to make these changes.")


if __name__ == "__main__":
    main()