#!/usr/bin/env bash
#
# start.sh -- launcher for PyTorchUI
# ----------------------------------------------------------------
# Generated by edit.py.  Edit at your own risk; regenerate with
#     python3 edit.py
# if you break something.
# ----------------------------------------------------------------

set -o pipefail

cd "$( dirname "${BASH_SOURCE[0]}" )" || { echo "cannot cd to script dir"; exit 1; }
ROOT="$PWD"
VERSION="0.1.0-alpha"

# ---------------------------------------------------------------- #
#  Colors                                                           #
# ---------------------------------------------------------------- #

use_colors=0
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    nc=$(tput colors 2>/dev/null || echo 0)
    if [[ "$nc" -ge 8 ]]; then
        use_colors=1
    fi
fi

if [[ "$use_colors" -eq 1 ]]; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RESET=$(tput sgr0)
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    MAGENTA=$(tput setaf 5)
    CYAN=$(tput setaf 6)
    WHITE=$(tput setaf 7)
else
    BOLD=""; DIM=""; RESET=""
    RED=""; GREEN=""; YELLOW=""; BLUE=""
    MAGENTA=""; CYAN=""; WHITE=""
fi

# ---------------------------------------------------------------- #
#  Logging                                                          #
# ---------------------------------------------------------------- #

QUIET=0
LOG_FILE=""

_log() {
    local line="$1"
    if [[ -n "$LOG_FILE" ]]; then
        printf '%s\n' "$line" >>"$LOG_FILE"
    fi
    if [[ "$QUIET" -eq 0 ]]; then
        printf '%s\n' "$line"
    fi
}

step()  { _log "${BLUE}${BOLD}==>${RESET} ${BOLD}$*${RESET}"; }
info()  { _log "    ${CYAN}$*${RESET}"; }
ok()    { _log "    ${GREEN}✓${RESET} $*"; }
warn()  { _log "    ${YELLOW}!${RESET} $*"; }
err()   { _log "    ${RED}✗${RESET} $*"; }
fatal() { err "$*"; exit 1; }

# ---------------------------------------------------------------- #
#  Banner                                                           #
# ---------------------------------------------------------------- #

banner() {
    [[ "$QUIET" -eq 1 ]] && return
    printf "\n"
    printf "  %s%sPyTorchUI%s  %s%s%s\n" \
        "$BOLD" "$WHITE" "$RESET" "$DIM" "$VERSION" "$RESET"
    printf "  %sVisual node editor for PyTorch pipelines%s\n" \
        "$CYAN" "$RESET"
    printf "  %s────────────────────────────────────────────────%s\n" \
        "$MAGENTA" "$RESET"
    printf "\n"
}

# ---------------------------------------------------------------- #
#  Help                                                             #
# ---------------------------------------------------------------- #

usage() {
    banner
    cat <<'HELP'
  COMMANDS
    run                Build (if needed) then launch the editor  [default]
    build              Rebuild data/main.db from installed libraries
    clean              Remove __pycache__, *.bak_*, autosave.json
    deps               Install requirements.txt
    test               Run the test suite
    doctor             Diagnose the environment
    reset              clean + build + run
    help               Show this help
    version            Print version

  OPTIONS
    -l, --libs LIST    Comma-separated libraries for build
    -nc, --no-cap      No cap on nodes per package
    -c,  --cap N       Cap nodes per package (default 2000)
    -nt, --no-torch    Skip torch during build
    -i,  --interactive Prompt for libraries and options
    -v,  --verbose     Verbose output
    -q,  --quiet       Suppress all non-error output
    --log FILE         Also write output to FILE
    -h,  --help        This message
    --version          Print version and exit

  EXAMPLES
    ./start.sh
    ./start.sh build -nc
    ./start.sh build -l "os,json,math"
    ./start.sh build -i
    ./start.sh build -nc -l "torch,transformers,tensorflow"
    ./start.sh clean && ./start.sh build && ./start.sh run
    ./start.sh doctor --log doctor.txt

HELP
}

# ---------------------------------------------------------------- #
#  Python interpreter detection                                     #
# ---------------------------------------------------------------- #

find_python() {
    local candidate
    for candidate in python python3; do
        if command -v "$candidate" >/dev/null 2>&1; then
            if "$candidate" -c "import PyQt5" >/dev/null 2>&1; then
                printf '%s\n' "$candidate"
                return 0
            fi
        fi
    done
    for candidate in python python3; do
        if command -v "$candidate" >/dev/null 2>&1; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

PYTHON="$(find_python)" || fatal "no python interpreter found in PATH"

# ---------------------------------------------------------------- #
#  Interactive library prompt                                       #
# ---------------------------------------------------------------- #

COMMON_LIBS=(
    "os" "json" "math" "random" "pathlib" "shutil" "time" "datetime"
    "torch" "torchvision" "torchaudio" "transformers" "tensorflow"
    "numpy" "scipy" "pandas" "matplotlib" "sklearn"
    "pyautogui" "PIL" "cv2"
)

prompt_libs() {
    step "Interactive library picker"
    info "Enter a comma-separated list of libraries."
    info "Common: ${COMMON_LIBS[*]}"
    printf "    %s> %s" "$MAGENTA" "$RESET"
    local answer
    read -r answer
    if [[ -n "$answer" ]]; then
        LIBS="$answer"
        ok "libraries: $LIBS"
    else
        info "no extra libraries"
    fi
    printf "    %sCap per package [%s]: %s" \
        "$MAGENTA" "${CAP:-2000}" "$RESET"
    read -r answer
    if [[ -n "$answer" ]]; then
        CAP="$answer"
    fi
    printf "    %sSkip torch? [y/N]: %s" "$MAGENTA" "$RESET"
    read -r answer
    case "$answer" in
        y|Y|yes|YES) NO_TORCH=1 ;;
    esac
    printf "    %sNo cap on all packages? [y/N]: %s" "$MAGENTA" "$RESET"
    read -r answer
    case "$answer" in
        y|Y|yes|YES) NO_CAP=1 ;;
    esac
    printf "\n"
}

# ---------------------------------------------------------------- #
#  Command: build                                                   #
# ---------------------------------------------------------------- #

cmd_build() {
    if [[ "$INTERACTIVE" -eq 1 ]]; then
        prompt_libs
    fi

    [[ -f "$ROOT/create.py" ]] || fatal "create.py not found in $ROOT"

    local args=( "$PYTHON" create.py --db )
    [[ "$VERBOSE" -eq 1 ]] || args+=( --quiet )
    [[ "$NO_CAP" -eq 1 ]] && args+=( --no-cap )
    if [[ -n "$CAP" ]]; then
        args+=( -c "$CAP" )
    fi
    [[ "$NO_TORCH" -eq 1 ]] && args+=( --no-torch )

    if [[ -n "$LIBS" ]]; then
        # Split on comma, add each as -l LIB
        local IFS=','
        local lib
        for lib in $LIBS; do
            # trim whitespace
            lib="$(printf '%s' "$lib" | tr -d ' ')"
            [[ -n "$lib" ]] && args+=( -l "$lib" )
        done
    fi

    step "Building data/main.db"
    info "$ ${args[*]}"
    if [[ -n "$LOG_FILE" ]]; then
        "${args[@]}" 2>&1 | tee -a "$LOG_FILE"
        local rc="${PIPESTATUS[0]}"
    else
        "${args[@]}"
        local rc=$?
    fi
    if [[ "$rc" -ne 0 ]]; then
        fatal "create.py exited with code $rc"
    fi

    if [[ -f "$ROOT/data/main.db" ]]; then
        local size
        size=$(stat -c '%s' "$ROOT/data/main.db" 2>/dev/null || echo "?")
        local rows
        rows=$("$PYTHON" - <<PYEOF
import sqlite3
try:
    c = sqlite3.connect("$ROOT/data/main.db")
    print(c.execute("SELECT COUNT(*) FROM nodes").fetchone()[0])
except Exception:
    print("?")
PYEOF
)
        ok "data/main.db: $rows nodes ($size bytes)"
    fi
}

# ---------------------------------------------------------------- #
#  Command: run                                                     #
# ---------------------------------------------------------------- #

cmd_run() {
    if [[ ! -f "$ROOT/data/main.db" && ! -f "$ROOT/main.db" ]]; then
        warn "no main.db found; building first"
        cmd_build
    fi
    step "Launching the editor"
    info "$ $PYTHON main.py"
    if [[ -n "$LOG_FILE" ]]; then
        "$PYTHON" "$ROOT/main.py" 2>&1 | tee -a "$LOG_FILE"
        return "${PIPESTATUS[0]}"
    else
        "$PYTHON" "$ROOT/main.py"
        return $?
    fi
}

# ---------------------------------------------------------------- #
#  Command: clean                                                   #
# ---------------------------------------------------------------- #

cmd_clean() {
    step "Cleaning generated files"
    local removed=0

    # __pycache__
    while IFS= read -r -d '' d; do
        rm -rf "$d"
        info "removed $d"
        removed=$((removed + 1))
    done < <(find "$ROOT" -type d -name __pycache__ -print0 2>/dev/null)

    # *.pyc
    while IFS= read -r -d '' f; do
        rm -f "$f"
        removed=$((removed + 1))
    done < <(find "$ROOT" -type f -name '*.pyc' -print0 2>/dev/null)

    # *.bak_*
    while IFS= read -r -d '' f; do
        rm -f "$f"
        info "removed $(basename "$f")"
        removed=$((removed + 1))
    done < <(find "$ROOT" -maxdepth 2 -type f -name '*.bak_*' -print0 2>/dev/null)

    # root-level strays
    for f in autosave.json generated.py; do
        if [[ -f "$ROOT/$f" ]]; then
            rm -f "$ROOT/$f"
            info "removed $f"
            removed=$((removed + 1))
        fi
    done

    ok "cleaned $removed item(s)"
}

# ---------------------------------------------------------------- #
#  Command: deps                                                    #
# ---------------------------------------------------------------- #

cmd_deps() {
    step "Installing dependencies"
    if [[ ! -f "$ROOT/requirements.txt" ]]; then
        warn "requirements.txt not found"
        info "generate it with:  python3 edit.py  (in the repo root)"
        return 1
    fi
    "$PYTHON" -m pip install -r "$ROOT/requirements.txt"
    ok "dependencies installed"
}

# ---------------------------------------------------------------- #
#  Command: test                                                    #
# ---------------------------------------------------------------- #

cmd_test() {
    step "Running tests"
    if [[ -d "$ROOT/tests" ]]; then
        "$PYTHON" -m pytest "$ROOT/tests" -q
    elif [[ -f "$ROOT/test.py" ]]; then
        "$PYTHON" "$ROOT/test.py"
    else
        warn "no tests found"
        return 1
    fi
}

# ---------------------------------------------------------------- #
#  Command: doctor                                                  #
# ---------------------------------------------------------------- #

cmd_doctor() {
    step "Diagnosing environment"
    printf "\n"

    info "Python: $("$PYTHON" --version 2>&1)  ($(command -v "$PYTHON"))"
    info "Root:   $ROOT"

    # session
    local session="${XDG_SESSION_TYPE:-unknown}"
    local display="${WAYLAND_DISPLAY:-${DISPLAY:-none}}"
    info "Session: $session  ($display)"
    if [[ "$session" == "wayland" ]]; then
        warn "Wayland session.  Qt uses XWayland for legacy clients."
        warn "Some X11 features (raw keyboard grab) may be limited."
    fi

    printf "\n"
    info "Dependencies:"
    local mod
    for mod in PyQt5 matplotlib torch numpy PIL pyautogui Xlib; do
        if "$PYTHON" -c "import $mod" >/dev/null 2>&1; then
            local ver
            ver=$("$PYTHON" -c "
try:
    import $mod as m
    print(getattr(m, '__version__', '?'))
except Exception:
    print('?')
" 2>/dev/null)
            ok "$mod  $ver"
        else
            warn "$mod  NOT installed"
        fi
    done

    printf "\n"
    info "Database:"
    if [[ -f "$ROOT/data/main.db" ]]; then
        local size rows
        size=$(stat -c '%s' "$ROOT/data/main.db" 2>/dev/null)
        rows=$("$PYTHON" - <<PYEOF
import sqlite3
try:
    c = sqlite3.connect("$ROOT/data/main.db")
    print(c.execute("SELECT COUNT(*) FROM nodes").fetchone()[0])
    fts = bool(c.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='node_search'"
    ).fetchone())
    print("fts5:", "yes" if fts else "no")
except Exception as e:
    print("?")
PYEOF
)
        ok "data/main.db  $size bytes"
        while IFS= read -r line; do info "$line"; done <<<"$rows"
    elif [[ -f "$ROOT/main.db" ]]; then
        warn "found legacy main.db at root — move it to data/main.db"
    else
        warn "no main.db — run  ./start.sh build"
    fi

    printf "\n"
    info "Groups:"
    local input_ok=0
    if id -nG | tr ' ' '\n' | grep -qx input; then
        ok "member of 'input' (evdev / raw keyboard available)"
        input_ok=1
    else
        warn "not in 'input' group"
        info "  run:  sudo usermod -a -G input \$USER"
        info "  then log out and back in"
    fi
    [[ "$input_ok" -eq 0 ]] && info "(this is optional — most nodes work without it)"

    printf "\n"
    info "Git:"
    if command -v git >/dev/null 2>&1 && [[ -d "$ROOT/.git" ]]; then
        local branch remote
        branch=$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null)
        remote=$(git -C "$ROOT" remote get-url origin 2>/dev/null || echo "none")
        ok "branch: $branch"
        info "remote: $remote"
        local dirty
        dirty=$(git -C "$ROOT" status --porcelain 2>/dev/null | wc -l)
        if [[ "$dirty" -gt 0 ]]; then
            warn "working tree has $dirty uncommitted change(s)"
        else
            ok "working tree clean"
        fi
    else
        warn "not a git repository"
    fi

    printf "\n"
    ok "diagnosis complete"
}

# ---------------------------------------------------------------- #
#  Command: reset                                                   #
# ---------------------------------------------------------------- #

cmd_reset() {
    cmd_clean
    printf "\n"
    cmd_build
    printf "\n"
    cmd_run
}

# ---------------------------------------------------------------- #
#  Argument parsing                                                 #
# ---------------------------------------------------------------- #

ACTION=""
LIBS=""
NO_CAP=0
CAP=""
NO_TORCH=0
INTERACTIVE=0
VERBOSE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        run|build|clean|deps|test|doctor|reset|help|version)
            ACTION="$1"; shift ;;
        --build)    ACTION="build"; shift ;;
        --run)      ACTION="run"; shift ;;
        --clean)    ACTION="clean"; shift ;;
        --deps)     ACTION="deps"; shift ;;
        --test)     ACTION="test"; shift ;;
        --doctor)   ACTION="doctor"; shift ;;
        --reset)    ACTION="reset"; shift ;;
        -l|--libs)  LIBS="$2"; shift 2 ;;
        -nc|--no-cap) NO_CAP=1; shift ;;
        -c|--cap)   CAP="$2"; shift 2 ;;
        -nt|--no-torch) NO_TORCH=1; shift ;;
        -i|--interactive) INTERACTIVE=1; shift ;;
        -v|--verbose) VERBOSE=1; shift ;;
        -q|--quiet) QUIET=1; shift ;;
        --log)      LOG_FILE="$2"; shift 2 ;;
        -h|--help)  ACTION="help"; shift ;;
        --version)  ACTION="version"; shift ;;
        --)         shift; break ;;
        -*)         err "unknown flag: $1"; usage; exit 2 ;;
        *)          err "unknown command: $1"; usage; exit 2 ;;
    esac
done

[[ -z "$ACTION" ]] && ACTION="run"

# ---------------------------------------------------------------- #
#  Dispatch                                                         #
# ---------------------------------------------------------------- #

case "$ACTION" in
    run)      banner; cmd_run ;;
    build)    banner; cmd_build ;;
    clean)    banner; cmd_clean ;;
    deps)     banner; cmd_deps ;;
    test)     banner; cmd_test ;;
    doctor)   banner; cmd_doctor ;;
    reset)    banner; cmd_reset ;;
    help)     usage ;;
    version)  printf "PyTorchUI %s\n" "$VERSION" ;;
    *)        fatal "unhandled action: $ACTION" ;;
esac

exit $?
